name: 'Issue Pull Request'
description: 'Creates pull request based on issue.'
inputs:
  issue:
    description: 'Number of issue which title used to create pull request.'
    required: true
  base:
    description: 'Base branch of new pull request.'
    default: master
    required: true
  head:
    description: 'Head branch to new pull request.'
    required: true
  body:
    description: 'Determines whether to copy body of issue to new pull request.'
    default: false
    required: true
  link:
    description: 'Determines whether to create comment to link pull request to specified issue.'
    default: false
    required: true
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  config:
    description: 'Path to file or config as value with generate settings. (Possible representation types: "Json" or "Yaml".)'
    default: |
      comment: 'Linked Issue: #{number}.'
    required: true
  context:
    description: 'Context can be specific value or file path, and can be accessed in text formatting context. (Possible representation types: "Json" or "Yaml".)'
    default: '{}'
    required: true
  output:
    description: 'Path to output result as file.'
    required: false
outputs:
  result:
    description: 'Action result.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'gray-dark'
